name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Decompress Project
        run: |
          unzip -q *.zip -d .
          echo "=== Files in root ==="
          ls -la

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          # الدخول للمجلد الفعلي للمشروع أينما كان
          if [ -d "neural_craft_flutter" ]; then cd neural_craft_flutter; fi
          if [ -d "extracted_project" ]; then cd extracted_project; fi
          
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App-APK
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
          
